const data = [
  { name: "Namibia", id: "NA" },
  { name: "Zimbabwe", id: "ZW" },
  { name: "Botswana", id: "BW" },
  { name: "Eswatini", id: "SZ" },
  { name: "Lesotho", id: "LS" },
  { name: "South Africa", id: "ZA" },
  { name: "Angola", id: "AO" },
  { name: "Zambia", id: "ZM" },
  { name: "Rwanda", id: "RW" },
  { name: "Somalia", id: "SO" },
  { name: "Morocco", id: "MA" },
  { name: "Tunisia", id: "TN" },
  { name: "Algeria", id: "DZ" },
  { name: "Libya", id: "LY" },
  { name: "Gambia", id: "GM" },
  { name: "Senegal", id: "SN" },
  { name: "Guinea-Bissau", id: "GW" },
  { name: "Central African Republic", id: "CF" },
  { name: "Nigeria", id: "NG" },
  { name: "Benin", id: "BJ" },
  { name: "Togo", id: "TG" },
  { name: "Cameroon", id: "CM" },
  { name: "Côte d'Ivoire", id: "CI" },
  { name: "Ghana", id: "GH" },
  { name: "Guinea", id: "GN" },
  { name: "Liberia", id: "LR" },
  { name: "Sierra Leone", id: "SL" },
  { name: "Western Sahara", id: "EH" },
  { name: "Mauritania", id: "MR" },
  { name: "Mali", id: "ML" },
  { name: "Burkina Faso", id: "BF" },
  { name: "Niger", id: "NE" },
  { name: "Chad", id: "TD" },
  { name: "Egypt", id: "EG" },
  { name: "Gabon", id: "GA" },
  { name: "Equatorial Guinea", id: "GQ" },
  { name: "Sudan", id: "SD" },
  { name: "Djibouti", id: "DJ" },
  { name: "Eritrea", id: "ER" },
  { name: "Ethiopia", id: "ET" },
  { name: "Lebanon", id: "LB" },
  { name: "Syrian Arab Republic", id: "SY" },
  { name: "Korea, Republic of", id: "KR" },
  { name: "Bangladesh", id: "BD" },
  { name: "India", id: "IN" },
  { name: "Mongolia", id: "MN" },
  { name: "Israel", id: "IL" },
  { name: "Jordan", id: "JO" },
  { name: "Kyrgyzstan", id: "KG" },
  { name: "Georgia", id: "GE" },
  { name: "Turkey", id: "TR" },
  { name: "Korea, Democratic People's Republic of", id: "KP" },
  { name: "Nepal", id: "NP" },
  { name: "Myanmar", id: "MM" },
  { name: "Bhutan", id: "BT" },
  { name: "Viet Nam", id: "VN" },
  { name: "Cambodia", id: "KH" },
  { name: "Lao People's Democratic Republic", id: "LA" },
  { name: "Thailand", id: "TH" },
  { name: "Poland", id: "PL" },
  { name: "Bosnia and Herzegovina", id: "BA" },
  { name: "Croatia", id: "HR" },
  { name: "Albania", id: "AL" },
  { name: "Austria", id: "AT" },
  { name: "Hungary", id: "HU" },
  { name: "Czechia", id: "CZ" },
  { name: "Slovakia", id: "SK" },
  { name: "Portugal", id: "PT" },
  { name: "Netherlands", id: "NL" },
  { name: "Luxembourg", id: "LU" },
  { name: "Belgium", id: "BE" },
  { name: "Romania", id: "RO" },
  { name: "Moldova, Republic of", id: "MD" },
  { name: "Bulgaria", id: "BG" },
  { name: "North Macedonia", id: "MK" },
  { name: "Ukraine", id: "UA" },
  { name: "Belarus", id: "BY" },
  { name: "Latvia", id: "LV" },
  { name: "Lithuania", id: "LT" },
  { name: "Switzerland", id: "CH" },
  { name: "Germany", id: "DE" },
  { name: "Finland", id: "FI" },
  { name: "Saudi Arabia", id: "SA" },
  { name: "Oman", id: "OM" },
  { name: "Qatar", id: "QA" },
  { name: "United Arab Emirates", id: "AE" },
  { name: "Malaysia", id: "MY" },
  { name: "Brunei Darussalam", id: "BN" },
  { name: "Iraq", id: "IQ" },
  { name: "Kuwait", id: "KW" },
  { name: "France", id: "FR" },
  { name: "El Salvador", id: "SV" },
  { name: "Honduras", id: "HN" },
  { name: "Mexico", id: "MX" },
  { name: "Guatemala", id: "GT" },
  { name: "Belize", id: "BZ" },
  { name: "Haiti", id: "HT" },
  { name: "Dominican Republic", id: "DO" },
  { name: "Nicaragua", id: "NI" },
  { name: "Costa Rica", id: "CR" },
  { name: "Panama", id: "PA" },
  { name: "Jamaica", id: "JM" },
  { name: "Puerto Rico", id: "PR" },
  { name: "Falkland Islands (Malvinas)", id: "FK" },
  { name: "Brazil", id: "BR" },
  { name: "Argentina", id: "AR" },
  { name: "Chile", id: "CL" },
  { name: "Paraguay", id: "PY" },
  { name: "Colombia", id: "CO" },
  { name: "Bolivia, Plurinational State of", id: "BO" },
  { name: "Peru", id: "PE" },
  { name: "Suriname", id: "SR" },
  { name: "Guyana", id: "GY" },
  { name: "French Guiana", id: "GF" },
  { name: "Uruguay", id: "UY" },
  { name: "Venezuela, Bolivarian Republic of", id: "VE" },
  { name: "Ecuador", id: "EC" },
  { name: "Greenland", id: "GL" },
  { name: "South Georgia and the South Sandwich Islands", id: "GS" },
  { name: "Canada", id: "CA" },
  { name: "United States of America", id: "US" },
  { name: "Spain", id: "ES" },
  { name: "Slovenia", id: "SI" },
  { name: "Greece", id: "GR" },
  { name: "Cyprus", id: "CY" },
  { name: "Iceland", id: "IS" },
  { name: "Ireland", id: "IE" },
  { name: "United Kingdom of Great Britain and Northern Ireland", id: "GB" },
  { name: "Denmark", id: "DK" },
  { name: "Sweden", id: "SE" },
  { name: "Estonia", id: "EE" },
  { name: "Kenya", id: "KE" },
  { name: "Uganda", id: "UG" },
  { name: "China", id: "CN" },
  { name: "Uzbekistan", id: "UZ" },
  { name: "Norway", id: "NO" },
  { name: "Japan", id: "JP" },
  { name: "Philippines", id: "PH" },
  { name: "Papua New Guinea", id: "PG" },
  { name: "Sri Lanka", id: "LK" },
  { name: "Madagascar", id: "MG" },
  { name: "Yemen", id: "YE" },
  { name: "Solomon Islands", id: "SB" },
  { name: "Australia", id: "AU" },
  { name: "New Zealand", id: "NZ" },
  { name: "Fiji", id: "FJ" },
  { name: "Turkmenistan", id: "TM" },
  { name: "Iran, Islamic Republic of", id: "IR" },
  { name: "Kazakhstan", id: "KZ" },
  { name: "Russian Federation", id: "RU" },
  { name: "Congo", id: "CG" },
  { name: "Burundi", id: "BI" },
  { name: "Mozambique", id: "MZ" },
  { name: "Tanzania, United Republic of", id: "TZ" },
  { name: "Malawi", id: "MW" },
  { name: "New Caledonia", id: "NC" },
  { name: "Tajikistan", id: "TJ" },
  { name: "Armenia", id: "AM" },
  { name: "Azerbaijan", id: "AZ" },
  { name: "Afghanistan", id: "AF" },
  { name: "Pakistan", id: "PK" },
  { name: "Indonesia", id: "ID" },
  { name: "Timor-Leste", id: "TL" },
  { name: "Italy", id: "IT" },
  { name: "Montenegro", id: "ME" },
  { name: "Serbia", id: "RS" },
  { name: "Cuba", id: "CU" },
];
export default data;
